### ISSUE TITLE
[Req for Info] Why there are no recent published releases?

### ISSUE THREAD

**Issue by BrainCrumbz** [zingchart/zingtouch#110]
Hi, hope that's ok to post this as an issue, we could not find the Discussions tab.

From a quick overview, the latest published NPM release is from March 2018. But then here on GH there are more recent commits, and they are not all about documentation, it seems there are code commits too.

Is there a reason why there are no more recent published releases?

Thanks

**Comment by lasabahebwa** [comment]
Hello @BrainCrumbz 

Thanks for reaching out. Yes, it's totally fine posting this as an issue. ZingTouch is open source software that had been shelved because of various reasons but we recently decided to resume it's development. The recent commits are small bug fixes from issues here and we're yet to update the package on npm.

Thanks for your patience.

**Comment by BrainCrumbz** [comment]
Thanks for clarification.

**Comment by lasabahebwa** [comment]
You're welcome
