### ISSUE TITLE
Direction Bug in Pan

### ISSUE THREAD

**Issue by jwdinker** [zingchart/zingtouch#13]
The PAN event will quit abruptly if the current direction is anything other than 360 degrees.  Not sure if this is an intended consequence.  

In the gif, the box is translating based off the distanceFromOrigin.  During the event, the conditions are to translate the element while the currentDirection is greater than 90 degrees and less than 270 degrees.  The first half of the gif shows the touch event abruptly quits.    

In second half of the gif, if I move the box at 360 degrees the touch event stays active. 

edit: After further research, it looks like I got it wrong.  If the targeted element reaches the origin coordinate of the touch event,the event will stop.   Looks like swipe right and left aren't possible. 

![directionbug](https://cloud.githubusercontent.com/assets/2313028/20041130/8ee275bc-a42a-11e6-9afe-599b7ff2a3c1.gif)

**Comment by mike-schultz** [comment]
Are you able to put this on something like jsfiddle? I can't seem to replicate, or perhaps I'm not 100% clear on understanding the use case. 

Just to note, `currentDirection` can give noisy results since it's translating user interactions. Even a slight twitch in the opposite direction, the `currentDirection` will output that value.

**Comment by tpowell** [comment]
Closed due to no follow-up
