### ISSUE TITLE
Get position informations for Pinch and Expand gestures

### ISSUE THREAD

**Issue by iwazaru** [zingchart/zingtouch#17]
I think it would be useful for Pinch and Expand gestures events to return coordinates of a point located a the center of the inputs that triggered the events. Coordinates should be in pixels with 0,0 being the top left of the ZingTouch Region.

Use case: when using Pinch and Expand gestures on an image to control its zoom level, you don't want to scale the image with it's center for [transform-origin](https://developer.mozilla.org/fr/docs/Web/CSS/transform-origin), you want to use a point located a the center of the user's fingers. Here's a good example: https://www.instagram.com/p/BJxv5WthYas/

Contrary to #16, I don't think this is something I can implement afterwards because the library doesn't seems to return any info about inputs position when pinch/expand gestures occurs.

**Comment by mike-schultz** [comment]
Hey, thanks for the suggestion. I do agree some sort of way to get a center point would be valuable like the use case you have showed. 

Im not so sure a reference to the Region would be best though. Region areas can be bigger than the element bound to the pinch/expand area. They're meant to act as a bleeding area since fingers are not precise. 

I did expose out a center point option in 988f787, if you wanted to try it out. It simply gets the midpoint and returns an x & y value based off the client. 

Also, if you need any more granular information about each event, the library exposes an array of `ZingEvents` on every emit, in addition to the distance and center point information. It will give the initial, current, and previous positions of the inputs allowing you to calculate just about anything.

**Comment by iwazaru** [comment]
It works great, thanks !
