### ISSUE TITLE
Pan event not called past initial bounding box of the child

### ISSUE THREAD

**Issue by nikkwong** [zingchart/zingtouch#25]
The drag event should continue past the target element, however in the following example—when dragged past the initial bounding box of the child, the `pan` callback stops firing:

https://jsfiddle.net/57LgL08q/1/

Is this a bug?

**Comment by mike-schultz** [comment]
Hey @nikkwong,

zingtouch currently does not support allowing events to be bound on an element and to have it's position modified within one "gesture state". A bit of the core's logic is written around coordinates of when an event initially started, rather than where it last came from. The Rotate gesture for example uses the initial point as a reference for rotational direction.

My suggestion would be to bind your gesture to a bounding box of the element you are trying to move, and handle the state of that element separately. The parent container should work just fine.

This example is a bit more extreme, but I'm using an overlay across the entire canvas to handle all events: http://codepen.io/zingchart/pen/RRpyJY.

**Comment by nikkwong** [comment]
That's great! Thanks for the info. It would be great if that was a bit clearer in the docs, because I wasted a bit of time on it. 

Cheers!

**Comment by mike-schultz** [comment]
will do!
