### ISSUE TITLE
End handler is being called on .pan even when .pan wasn't fired

### ISSUE THREAD

**Issue by nikkwong** [zingchart/zingtouch#27]
Hi, please see the following pen:

https://codepen.io/anon/pen/awwOVR

Basically we should not expect the function for ```pan.end``` to be called when the gesture itself wasn't fired (as numInputs: 2, a click does not fire the ```pan```).

**Comment by mike-schultz** [comment]
The lifecycle of the library iterates through each start/move/end hook of each registered gesture and evaluates each function, regardless of what occurred in the previous life cycle step. Each lifecycle hook function either returns an object that should be emitted to the end user, or null to not be emitted.

I'm assuming you have a more complex use case for pan, and need to hook into the `end` event. You'll need to do some logic manually since you're overriding the event hook itself. `this` is available in the life cycle hook and allows you to see and passed in internal variables, like `numInputs`

I have a more complex example of how I've used the lifecycle events here: https://codepen.io/zingchart/pen/RRpyJY?editors=1010

**Comment by nikkwong** [comment]
Thanks for responding. Ok I see, so basically you would suggest adding a statement in the ```end``` function to ```return``` if ```numInputs < 2```?

**Comment by mike-schultz** [comment]
Yeah that would be the best approach
